### ISSUE TITLE
Cannot update object with OneToMany relationship

### ISSUE THREAD

**Issue by jbcpollak** [la-team/light-admin#143]
I have two objects, a `Job` and a `JobQueue`, which contains a job, like this:

```
@JsonIgnore
@ManyToOne(targetEntity = Job.class)
@JoinColumn(name = "job_id", referencedColumnName = "jobId") //TODO check on the cascading
private Job job;
```

In our database, we have a foreign key constraint that requires JobQueue.job_id to be not null, and refer to a valid Job.

In LightAdmin, I created a Job, then went to the JobQueue page and created a JobQueue, and chose the Job from the dropdown. When I clicked save, I got this error in the UI:

```
    "could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
```

And this error in the log file:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'job_id' cannot be null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0]
```

When I added '@NotNull' to the definition of the Job in the JobQueue object, and now when I click 'save', I get a UI validation error, "Required". So LightAdmin knows the field is empty, which is strange, since I chose a Job from the dropdown.

When I use the Chrome debugger I see this request payload being sent to the server:

```
job: "http://localhost:9090/admin/rest/jobs/5"
scheduledTime: "2014-09-23"
sendTime: "2014-09-11"
```

With this response:

```
{
  "errors" : [ {
    "entity" : "JobQueue",
    "message" : "Required",
    "invalidValue" : "null",
    "property" : "job"
  } ]
}
```

I verified that http://localhost:9090/admin/rest/jobs/5 is a valid URL, and it returns the job I referenced.

I checked out LightAdmin-Demo, and got it working, and it does not have this problem. I modified my code to be more like the demo, but the problem continues.

**Comment by yaminim1** [comment]
CHeck

**Comment by AneeNigitha** [comment]
gjhkjlk;l;;lk
