### ISSUE TITLE
can't run this application

### ISSUE THREAD

**Issue by mlotfi2005** [la-team/light-admin#166]
Hi,
I am new here and still learning, maybe I missed something, I followed the steps, but when I got to 

Navigate into demo application directory:
$ cd lightadmin-demo

I did not see any directory called lightadmin-demo.

I tried everywhere to run tomcat:run but always getting :+1: 

C:\Users\alotfi\workspaceJPA\light-admin\lightadmin-tests>mvn tomcat7:run
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'tomcat7'.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.apache.maven.plugins:maven-tomcat7-plugin' does not exist or no valid version could be found
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Mon Nov 17 13:24:35 EST 2014
[INFO] Final Memory: 5M/122M
[INFO] ------------------------------------------------------------------------
C:\Users\alotfi\workspaceJPA\light-admin\lightadmin-tests>

**Comment by indyaah** [comment]
@mlotfi2005  : The directory you are trying is tests module

Try : https://github.com/la-team/lightadmin-demo.

**Comment by lazaridis-com** [comment]
@mlotfi2005 , @max-dev , this can be closed.
