### ISSUE TITLE
Please Clarify if this Project is Dropped

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#175]
It seems that there are no commits/answers from the main author @max-dev.

Can you please clarify the status of the project?

**Comment by velikanov** [comment]
:+1: hope that @max-dev is fine

**Comment by lazaridis-com** [comment]
He seems alive: https://github.com/max-dev?tab=activity

But strangly, even an email question subjecting lightadmin professional support remained unanswered.

**Comment by lazaridis-com** [comment]
see #178

**Comment by max-dev** [comment]
Sorry, mates. I was heavily overloaded with commercial project I'm working on.
The good news is that I'm not going to drop LA, but any contributors help would be much appreciated.
Please contact me, if you have any desire to join the project.

**Comment by velikanov** [comment]
yay Max!!! first of all thank you for great project! the second is thank you that you are fine! :+1:
