### ISSUE TITLE
[PROJECT] Any Users Interested to contribute to this Project?

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#178]
It seems the developer has dropped this project.

Are there any users/developers there, interested to update light-admin to work with latest spring-boot?

I would start some work on a fork, but it seems the effort is quite high, and thus I'd like to share it.

**Comment by rafalwrzeszcz** [comment]
I never like forks, maybe try to contact developer on the Google Goups? https://groups.google.com/forum/#!forum/lightadmin Maybe a regular take over is possible to save the flow and all the user-base. I rememer that that was the best way to contact him/them. I'm more than interested, but I hardly have time for spare time projects, so I won't probably participate actively...

**Comment by lazaridis-com** [comment]
yes, please try on the group (although there's zero response since Dec. 2014). see additionally #175. Some former team members said he's fine, but just very busy with his job.

**Comment by lazaridis-com** [comment]
btw.:  the goal would be to simply update to latest versions (#177) and to use maven-dependency mechanism ( #176).

**Comment by max-dev** [comment]
@lazaridis-com @rafalwrzeszcz Sorry, mates. I was heavily overloaded with commercial project I'm working on.
The good news is that I'm not going to drop LA (I did several attempts to upgrade spring-related artifacts  versions with one shot, but IMHO it needs more time & attention than I had). 
Any contributors help would be much appreciated.
Please contact me, if you have any desire to join the project as a contributor.

**Comment by lazaridis-com** [comment]
@max-dev , I had contacted you already via email. If upgrading makes difficulties, then possibly the first step would be to create a plan with step-by-step updates (thus it becomes multiple smaller chunks of work, rather than one large and difficult chunk.

**Comment by lazaridis-com** [comment]
Example:

- update Java8
- update to same version of spring-boot, but using the spring-platform
- update **one** version of spring-boot at a time, until the latest version is reached.

**Comment by max-dev** [comment]
I need to take a closer look at it, but as far as I remember, upgrading to the latest Spring Data required the highest efforts. After finishing this, it won't be a problem to adapt LA for using with the latest Spring Boot.
BTW, what kind of problems you had during upgrade?

**Comment by lazaridis-com** [comment]
I don't remember exactly. Out of experience, a "stay away, it's too much" alert came up.

**Comment by max-dev** [comment]
Yeah, it's not an easy part. LA was started with Spring Data REST 1.X.X version, which was made in 'prototype' mode. Upgrading to the version 2.X.X required me to redesign & refactor too much LA code without adding any features. It was a hard time, really :)

**Comment by max-dev** [comment]
Current Spring Data version is 2.3.0 and they already have a stable design, which makes an upgrade much easier.

**Comment by lazaridis-com** [comment]
So, is it finally possibly easier to update the code in one chunk to latest spring-boot / spring-platform?

**Comment by max-dev** [comment]
As I said before: 
 - Spring Data JPA/REST upgrade (the hardest part, 'cause LA heavily relies on them)
 - Introducing to Spring Platform
 - Adapting to Spring Boot

**Comment by max-dev** [comment]
> Are there any users/developers there, interested to update light-admin to work with latest spring-boot?
> I would start some work on a fork, but it seems the effort is quite high, and thus I'd like to share it.
Is it still relevant for you?

**Comment by lazaridis-com** [comment]
This was for the case that you're not reachable. Of course you're the 1st choice to do the upgrade, but I'm available to assist a bit.

**Comment by lazaridis-com** [comment]
(I could possibly start a step by step upgrade on a fork, and you jump in whenever I hit on a serious problem. This way I can avoid a deeper teach-in to the code).

**Comment by max-dev** [comment]
Agreed.

**Comment by lazaridis-com** [comment]
Ok, very nice. (follow-up: #177)

**Comment by velikanov** [comment]
:+1:

**Comment by lazaridis-com** [comment]
(note that this is not about spring-data-rest update alone, but about an update to spring-platform.

**Comment by max-dev** [comment]
Yes, spring-platform will be the second step.

**Comment by lazaridis-com** [comment]
Current platfom has spring-data 2.2.2.RELEASE. In any way, they way I would process is filed here: #177. If you feel that you need to update spring-data-rest alone, then please do it this way. I personally need to take a more careful process (as I don't know the sources, and neither want to make a full teach-in)
