### ISSUE TITLE
How do I start the Tests?

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#195]
What kind of tests are included in the sources, and how do I start them?

Do I need to start firefox myself?

Do I need to start the sandbox example myself?

**Comment by ikostenko** [comment]
The UI tests can be started in two modes - developer's mode (when LightAdmin Sandbox starts automatically before the tests), and in test mode - when LightAdmin Sandbox should be started manually before the tests start.
To start in dev mode, run the following command from `lightadmin-tests` directory: `mvn clean install -Dcontainer.port=8080 -P dev-mode`
To start in tests mode, first start the LightAdmin Sandbox by issuing the following command from `ightadmin-sandbox` directory: `tomcat7:run`, and then, start the UI tests from `lightadmin-tests` directory: `clean install -P test-mode`

**Comment by jimmyfm** [comment]
Which (for future reference) is also very clearly explained here:
https://github.com/la-team/light-admin/blob/master/README.md

**Comment by lazaridis-com** [comment]
@jimmyfm , no, it's not yet very clear, that's why I asked the original developer / test-manager. But I'll update the doc (will be moved to DEV.md, to separated usage-doc from development-doc).
