### ISSUE TITLE
Update apache tiles

### ISSUE THREAD

**Issue by lazaridis-com** [la-team/light-admin#196]
Currently used:

<apache.tiles.version>2.2.2</apache.tiles.version>

need to be updated to: 3.0.5

This introduces some code changes, and I currently want to stay out of digging into code.

Anyone can do this task?

- [ ] update lightadmin-core to apache.tiles 3.0.5
- [ ] update lightadmin-boot pom (remove 2.2.2 versions from dependencyManagement)
- [ ] update lightadmin-sandbox pom ( " )

**Comment by max-dev** [comment]
We're considering porting LA UI to backbone/angular. Updating to Tiles 3.x.x is not in release plan.

**Comment by jimmyfm** [comment]
I would use one of the standard spring template engines instead of adding another piece to the stack needed to this project.

It would be great if LA would be able to work and integrate seamlessly with spring, it would be an amazing tool very useful since the very early stages of development just like "contrib.admin" is for django.

**Comment by lazaridis-com** [comment]
@max-dev , understand that this issue addresses **contributors** (and not "Your Majesty" Master of the Buttons) which are intrested to bring this piece of software towards a **full** spring-platform-1.1.2 compatible release.

So, why don't you stop beeing delusional (talking about `release-plans`, whilst this project isn't even working in the  basics), or at least stop closing issues, thus they stay on the radar of interested parties?

@jimmyfm , what you suggest is of cours 100% rational and valid, but don't expect that you'll be heard here. As mentioned within #172, I'll continue this on my repo, at least towards a stable spring-platform-1.1.2 version, for which I need some assistance of users and/or developers.

**Comment by lazaridis-com** [comment]
@jimmyfm , if you find the time, can you look at the code in order to assess the **effort** for a ui-system migration (e.g. tiles to thymeleaf) ?
