### ISSUE TITLE
maven repository does not work

### ISSUE THREAD

**Issue by neoqing** [la-team/light-admin#232]
Hi,There:
  I tried couple time, but the maven repository does not work, I have tried
http://lightadmin.org/nexus/content/repositories/releases
and
http://lightadmin.org/nexus/content/repositories/snapshots

Is there anyone can help? thanks a lot.

Neo

**Comment by max-dev** [comment]
Hi Neo,
Sorry for inconvenience - Fixed now.

**Comment by neoqing** [comment]
Thx,I will try it and update later.

发自我的 iPhone
