### ISSUE TITLE
Unable to transfer files from lightadmin.org  repository

### ISSUE THREAD

**Issue by tilhari95** [la-team/light-admin#261]
While trying out lightadmin-spring-travel demo. On running **mvn clean install** following Bad Gateway problem is reported on several steps:

> Failure to transfer org.lightadmin:lightadmin:1.0.0-SNAPSHOT/maven-metadata.xml from http://lightadmin.org/nexus/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of lightadmin-nexus-releases has elapsed or updates are forced. Original error: Could not transfer metadata org.lightadmin:lightadmin:1.0.0-SNAPSHOT/maven-metadata.xml from/to lightadmin-nexus-releases (http://lightadmin.org/nexus/content/repositories/releases): Failed to transfer file: http://lightadmin.org/nexus/content/repositories/releases/org/lightadmin/lightadmin/1.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 502 , ReasonPhrase:Bad Gateway.

**Comment by palaman** [comment]
+1

**Comment by keyboardsamurai** [comment]
Same here. Any workarounds?

**Comment by tilhari95** [comment]
This product looks left off !!!!
No new commits or version upgrade from a long time.
I need a tool more or less like this one.
Any help !!

**Comment by palaman** [comment]
It's working again! Thanks for a great product

**Comment by tilhari95** [comment]
yes its working now..!!

**Comment by ammad27k** [comment]
Failed to transfer file: http://lightadmin.org/nexus/content/repositories/snapshots "Service Temporary Unavailable"

Can any body have an idea what i can do now ?
