### ISSUE TITLE
Light Admin Domain Expired

### ISSUE THREAD

**Issue by allnash** [la-team/light-admin#266]
I think the domain name http://lightadmin.org seems to have expired.

You may want to renew it.

**Comment by allnash** [comment]
@max-dev  @volkan @akurdyukov @jimmyfm @elwin013

**Comment by timminss** [comment]
Is there another URL I can use in the meantime in my pom?

**Comment by jimmyfm** [comment]
You can either clone the project in your computer and do "mvn install", this will install the artifact in your local repo. Works in many cases, not if you deploy in Heroku or similar environments.

In that case you can use jitpack, it's all clearly explained here [https://jitpack.io/#la-team/light-admin](url)

**Comment by max-dev** [comment]
@allnash @jimmyfm @timminss thanks - FIXED
